### ISSUE TITLE
Virtual Contact generation errors

### ISSUE THREAD

**Issue by alecive** [alecive/periPersonalSpace#15]
When running `virtualContactGenerator` module, I get the following:
```
 virtualContactGeneration --skin_parts::SKIN_LEFT_FOREARM on --robot icubSim
...
[INFO]Module name set to virtualContactGeneration
[INFO]Robot is: icubSim
[INFO]virtContactGenThread rateThread working at 100 ms.
[INFO]verbosity set to 0
[INFO]Type is: random
[INFO]Adding SKIN_LEFT_HAND to active skin parts.
[INFO]Adding SKIN_LEFT_FOREARM to active skin parts.
[INFO]SKIN_EVENTS section found
yarp: Port /virtualContactGeneration/virtualContacts:o active at tcp://10.255.72.152:10056
[ERROR][virtContactGenerationThread] Asked to initialize skinDynLib::SkinPart:: 2, but that skin part is not implemented yet.
[ERROR][virtContactGenerationThread] activeSkinPartsNames and activeSkinParts have different size (2 vs. 1).
[INFO]virtContactGenThrd instantiated...
Floating point exception (core dumped)
```

Two issues are there:
 1. The `yError` that is printed out should be solved
 2. The thread should exit before encountering the exception. By simply returning false after https://github.com/alecive/periPersonalSpace/blob/master/modules/virtualContactGeneration/virtContactGenThread.cpp#L131 should be sufficient. Maybe it would be useful to handle also the return false on `initSkinParts()`, i.e. close the module at #L126

**Comment by matejhof** [comment]
good point! 
Solved second part - proper closing.
Will work on first part - the forearms were really simply not implemented.

**Comment by matejhof** [comment]
Should be solved now, you can test.
