### ISSUE TITLE
Add flag to enable/disable velocity handling

### ISSUE THREAD

**Issue by pattacini** [alecive/periPersonalSpace#3]
At a certain point we have to make the software configurable in order to enable/disable the handling of second axis (i.e velocity), to then merge `dev` into `master`.

**Comment by alecive** [comment]
After a proper set of testing, I would consider this fixed on branch `1d2deq3d` after commit d60c764c8b57ba8836fb740aa97afe2a2f75b39e . I'll keep this branching until I'll be 100% of not losing any feature and not having any new bug, but I would say that we're there.

**Comment by alecive** [comment]
Closing because everything has been merged in master right now.
